apiVersion: v1
kind: Service
metadata:
  name: {{ template "voting-app.fullname" .}}-svc
  release: {{ .Release.Name }}
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: {{ .Values.frontendApp.name }}